### PR TITLE
Fix tests on macOS M1

### LINKED ISSUE #16: Fix tests on macOS M1.
Upgrade `jnr-ffi` to allow running on newer macOS versions (which require for signed binaries).
Disable tests for macOS for unsupported system calls.

### PR DESCRIPTION
**Pull request by maxim-ponomarev**
Upgrade 'jnr-ffi' to allow running on newer macOS versions (which req…uire for signed binaries
Disable tests for macOS for unsupported system calls.
Fix #16

### CODE REVIEW

File: src/test/java/net/openhft/posix/internal/jnr/JNRPosixAPITest.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ public void open() throws IOException {
         assertEquals(0, jnr.lseek(fd, 0, WhenceFlag.SEEK_SET));
         assertEquals(-1, jnr.lseek(fd, 16, WhenceFlag.SEEK_DATA));
         assertEquals(0, jnr.ftruncate(fd, 4096));
-        if (jnr instanceof JNRPosixAPI) {
+        if (jnr instanceof JNRPosixAPI && !OS.isMacOSX()) {
```
Comment (JerryShea) [inline src/test/java/net/openhft/posix/internal/jnr/JNRPosixAPITest.java]: what does this mean?

File: src/test/java/net/openhft/posix/internal/jnr/JNRPosixAPITest.java [hunk 2]
```diff
@@ -109,6 +109,8 @@ public void mmap_sync() throws IOException {
 
     @Test
     public void mlockall() {
+        assumeFalse(OS.isMacOSX());
```
Comment (JerryShea) [inline src/test/java/net/openhft/posix/internal/jnr/JNRPosixAPITest.java]: suggest `assumeFalse("explanation", ....`

**Review by rogersimmons — APPROVED** [review]

**Review by JerryShea — APPROVED** [review]
